import { NavItem } from '../types';

export const NAVIGATION_ITEMS: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/',
    icon: 'LayoutDashboard',
    category: 'Core Operations',
    priorityForRoles: ['super_admin', 'admin', 'management', 'project_manager'],
  },
  {
    id: 'crm',
    label: 'CRM',
    path: '/crm/leads',
    icon: 'Users2',
    category: 'Sales & Pre-Construction',
    badge: '12',
    badgeVariant: 'warning',
    priorityForRoles: ['sales', 'super_admin', 'admin'],
    children: [
      { id: 'analytics', label: 'CRM Cockpit', path: '/crm/analytics' },
      { id: 'leads', label: 'Leads Pipeline', path: '/crm/leads', count: 25 },
      { id: 'follow-ups', label: 'Follow-ups', path: '/crm/follow-ups', count: 6 },
      { id: 'site-visits', label: 'Site Visits', path: '/crm/site-visits', count: 8 },
      { id: 'customers', label: 'Customers', path: '/crm/customers', count: 15 },
    ],
  },
  {
    id: 'estimation',
    label: 'Estimation',
    path: '/estimation/estimates',
    icon: 'Calculator',
    category: 'Sales & Pre-Construction',
    priorityForRoles: ['estimation_engineer', 'qs', 'project_manager', 'super_admin'],
    children: [
      { id: 'estimates', label: 'Estimates', path: '/estimation/estimates' },
      { id: 'boq', label: 'BOQ', path: '/estimation/boq' },
      { id: 'rate-analysis', label: 'Rate Analysis', path: '/estimation/rate-analysis' },
      { id: 'quotations', label: 'Quotations', path: '/estimation/quotations' },
    ],
  },
  {
    id: 'tenders',
    label: 'Tenders',
    path: '/tenders',
    icon: 'ScrollText',
    category: 'Sales & Pre-Construction',
    badge: '3',
    badgeVariant: 'info',
    priorityForRoles: ['estimation_engineer', 'sales', 'super_admin'],
  },
  {
    id: 'contracts',
    label: 'Contracts',
    path: '/contracts',
    icon: 'FileCheck',
    category: 'Sales & Pre-Construction',
    priorityForRoles: ['super_admin', 'management', 'project_manager'],
  },
  {
    id: 'projects',
    label: 'Projects',
    path: '/projects',
    icon: 'HardHat',
    category: 'Site & Project Execution',
    badge: '6 Active',
    badgeVariant: 'success',
    priorityForRoles: ['site_engineer', 'civil_engineer', 'project_manager', 'super_admin', 'subcontractor'],
    children: [
      { id: 'all-projects', label: 'Projects', path: '/projects' },
      { id: 'planning', label: 'Planning', path: '/projects/planning' },
      { id: 'tasks', label: 'Tasks', path: '/projects/tasks' },
      { id: 'dpr', label: 'DPR', path: '/projects/dpr', count: 'Due' },
      { id: 'progress', label: 'Progress', path: '/projects/progress' },
      { id: 'measurements', label: 'Measurements', path: '/projects/measurements' },
      { id: 'rfi', label: 'RFI', path: '/projects/rfi' },
      { id: 'variations', label: 'Variations', path: '/projects/variations' },
      { id: 'handover', label: 'Handover', path: '/projects/handover' },
    ],
  },
  {
    id: 'procurement',
    label: 'Procurement',
    path: '/procurement/purchase-requests',
    icon: 'ShoppingBag',
    category: 'Supply Chain & Inventory',
    badge: '5 POs',
    badgeVariant: 'warning',
    priorityForRoles: ['purchase_manager', 'store_manager', 'accounts', 'super_admin'],
    children: [
      { id: 'purchase-requests', label: 'Purchase Requests', path: '/procurement/purchase-requests' },
      { id: 'rfq', label: 'RFQ', path: '/procurement/rfq' },
      { id: 'vendor-comparison', label: 'Vendor Comparison', path: '/procurement/vendor-comparison' },
      { id: 'purchase-orders', label: 'Purchase Orders', path: '/procurement/purchase-orders' },
      { id: 'grn', label: 'GRN', path: '/procurement/grn' },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    path: '/inventory/materials',
    icon: 'Boxes',
    category: 'Supply Chain & Inventory',
    priorityForRoles: ['store_manager', 'purchase_manager', 'site_engineer'],
    children: [
      { id: 'materials', label: 'Materials', path: '/inventory/materials' },
      { id: 'stock', label: 'Stock Dashboard', path: '/inventory/stock' },
      { id: 'stock-issue', label: 'Site Issue', path: '/inventory/stock-issue' },
      { id: 'stock-transfer', label: 'Transfer', path: '/inventory/stock-transfer' },
      { id: 'stock-adjustment', label: 'Adjustment', path: '/inventory/stock-adjustment' },
      { id: 'forecasting', label: '🧠 Forecasting', path: '/inventory/forecasting' },
    ],
  },
  {
    id: 'vendors',
    label: 'Vendors',
    path: '/vendors',
    icon: 'Truck',
    category: 'Supply Chain & Inventory',
    priorityForRoles: ['purchase_manager', 'super_admin'],
  },
  {
    id: 'subcontractors',
    label: 'Subcontractors',
    path: '/subcontractors',
    icon: 'Building',
    category: 'Resource Management',
    priorityForRoles: ['project_manager', 'qs', 'super_admin'],
  },
  {
    id: 'labour',
    label: 'Labour',
    path: '/labour',
    icon: 'Users',
    category: 'Resource Management',
    priorityForRoles: ['site_engineer', 'hr', 'safety_officer'],
  },
  {
    id: 'equipment',
    label: 'Equipment',
    path: '/equipment',
    icon: 'Wrench',
    category: 'Resource Management',
    priorityForRoles: ['site_engineer', 'civil_engineer', 'project_manager'],
    children: [
      { id: 'equipment-fleet', label: 'Fleet', path: '/equipment/fleet' },
      { id: 'equipment-fuel', label: 'Fuel Log', path: '/equipment/fuel' },
      { id: 'equipment-maintenance', label: 'Maintenance', path: '/equipment/maintenance' },
    ],
  },
  {
    id: 'safety',
    label: 'Safety',
    path: '/safety',
    icon: 'ShieldAlert',
    category: 'Compliance & Quality',
    badge: '0 Incidents',
    badgeVariant: 'success',
    priorityForRoles: ['safety_officer', 'site_engineer', 'project_manager', 'super_admin'],
  },
  {
    id: 'quality',
    label: 'Quality',
    path: '/quality',
    icon: 'CheckCircle2',
    category: 'Compliance & Quality',
    priorityForRoles: ['safety_officer', 'site_engineer', 'civil_engineer', 'super_admin'],
  },
  {
    id: 'documents',
    label: 'Documents (incl. Drawings)',
    path: '/documents',
    icon: 'FolderKanban',
    category: 'Compliance & Quality',
    priorityForRoles: ['civil_engineer', 'site_engineer', 'project_manager', 'client'],
  },
  {
    id: 'billing',
    label: 'Billing',
    path: '/billing/ra-bills',
    icon: 'Receipt',
    category: 'Finance & Accounts',
    priorityForRoles: ['accounts', 'qs', 'project_manager', 'client', 'super_admin'],
    children: [
      { id: 'ra-bills', label: 'RA Bills', path: '/billing/ra-bills' },
      { id: 'client-billing', label: 'Client Billing', path: '/billing/client-billing' },
    ],
  },
  {
    id: 'accounts',
    label: 'Accounts',
    path: '/accounts/receivables',
    icon: 'Coins',
    category: 'Finance & Accounts',
    priorityForRoles: ['accounts', 'super_admin', 'management'],
    children: [
      { id: 'receivables', label: 'Receivables', path: '/accounts/receivables' },
      { id: 'payables', label: 'Payables', path: '/accounts/payables' },
      { id: 'expenses', label: 'Expenses', path: '/accounts/expenses' },
      { id: 'petty-cash', label: 'Petty Cash', path: '/accounts/petty-cash' },
      { id: 'bank', label: 'Bank & Escrow', path: '/accounts/bank' },
      { id: 'transactions', label: 'Payments & Receipts', path: '/accounts/transactions' },
      { id: 'journal', label: 'Journal', path: '/accounts/journal' },
    ],
  },
  {
    id: 'hr',
    label: 'HR',
    path: '/hr/employees',
    icon: 'UserCheck',
    category: 'Organization & Admin',
    priorityForRoles: ['hr', 'super_admin'],
    children: [
      { id: 'employees', label: 'Employees', path: '/hr/employees' },
      { id: 'attendance', label: 'Attendance', path: '/hr/attendance' },
      { id: 'leave', label: 'Leave', path: '/hr/leave' },
      { id: 'payroll', label: 'Payroll', path: '/hr/payroll' },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    path: '/reports/budget-vs-actual',
    icon: 'BarChart3',
    category: 'Organization & Admin',
    priorityForRoles: ['super_admin', 'management', 'accounts', 'project_manager'],
    children: [
      { id: 'budget-vs-actual', label: 'Budget vs Actual', path: '/reports/budget-vs-actual' },
    ],
  },
  {
    id: 'client-portal',
    label: 'Client Portal',
    path: '/client-portal',
    icon: 'ExternalLink',
    category: 'External Access',
    priorityForRoles: ['client'],
  },
  {
    id: 'settings',
    label: 'Settings',
    path: '/settings/company',
    icon: 'Settings',
    category: 'Organization & Admin',
    priorityForRoles: ['super_admin', 'admin'],
    children: [
      { id: 'company', label: 'Company', path: '/settings/company' },
      { id: 'users', label: 'Users & Roles', path: '/settings/users' },
      { id: 'permissions', label: 'Permissions', path: '/settings/permissions' },
      { id: 'audit-log', label: 'Audit Log', path: '/settings/audit-log' },
    ],
  },
];
